### PR TITLE
Fix bug where DOB can be later than admission date

### LINKED ISSUE #46: Fix DOB after admission date

### LINKED ISSUE #47: Edit command not working properly
The edit command is currently not working properly according to updated parameters for each Person. 
More specifically, the DOB of a person can be edited such that it is later than the admission date. This is not allowed.

Changes need to be made and new testcases to be added.

### PR DESCRIPTION
**Pull request by iamtr**
Fixes #46
Fixes #47

This PR will fix the bug in AddCommand, where users are able to add a person with a DOB that is later than Admission Date
This is also modified for EditCommand, where users are able to modify an existing person s.t. their DOB is later than Admission Date.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -86,6 +88,14 @@ public CommandResult execute(Model model) throws CommandException {
...
         }
 
+        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
+
+        LocalDate dobToCheck = LocalDate.parse(editedPerson.getDob().value, formatter);
+        LocalDate adToCheck = LocalDate.parse(editedPerson.getAdmissionDate().value, formatter);
+        if (dobToCheck.isAfter(adToCheck)) {
+            throw new CommandException(Messages.MESSAGE_DOB_LATER_THAN_ADMISSION);
+        }
+
```
Comment (swtan346) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:98]: Will it be better if dob > admission date only when dob or admission date is modified, instead of checking for every edit command?

**Review by swtan346 — APPROVED** [review]
Good job 👍
